sudo: false
language: rust
rust:
- nightly
- beta
matrix:
  include:
  - rust: stable
    env: LINT=true
  allow_failures:
  - rust: nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test -- --features test-external-apis &&
  travis-cargo bench &&
  travis-cargo --only stable doc
- git diff --exit-code
- |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    rustup component add rustfmt
    rustup component add clippy
    set -x
    cargo fmt --all -- --check
    cargo clippy -- -D warnings -A deprecated
  fi
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- travis-cargo --only stable doc-upload
- env COVERAGE_TESTING=1 travis-cargo --only stable coveralls --no-sudo
notifications:
  email:
    on_success: never
env:
  global:
  - secure: XXYE8x015gOSJ+DD9FeCdEKQTeU6mZ5j47Nh1ncZTkdN6+RnrN/DxAwccvh9u6t8/V6WN868AHIvTc0nA031mqwnh6vcQDr3Ak8ydJCTM8KFgwsuESokSZYkbiiQd/FWTBri/P9H5jejCw3aSFQZUVeCpu2Zxp0N9/Jn3ky7NVknBOVdz21jRC/KivBkpbvOCj8iEtGZuYSQu3Gpq1wbuZaqDdgg6JVvrYy7LbUNGe0rHMjCcyuiutqp6R8zIQoC7p2kmoHkXrTaDKQrpmSi+uLJJE7KqML9tFFnvjvmgroRYDCk0gc/fr/GunikvUkcczBBSsVXWj66EpriQxwdEnI1uhNtKUOGALIAMiLz2k0rbLl1wFLOvFlhEPhDGvt+mw+h2BIxoyy9mwVioYym7V8pksw0UuCuLuyAp1Rc89iT6/N3HfMFPZeTBeudktUb5ijHgJyobVwakxKXgKqELbrhUhmzBf8fwtmPH+Lnganyrz4qcKBnuUl2fSp6MIaGIeSZZwigggV8QSXw9u/1c32RhQs47ZDRJX2lzEzVyAVZ0liyn32hWFI6Ctur4jNV7LWtOcDqdYZZfqyZOL/HehNFtDoJfrYsp/KZvmBipmOkrNsKCKEAdvUoeTDXo4ME31tjGtiPbHIdRuBJJqt38gm1AKyoVJKp2KFGDsI0djA=
branches:
  except:
  - staging.tmp
  - staging-squash-merge.tmp
